layout_spectrum: 0.7276596
typography_spectrum: 0.5765957
color:
  saturation: 0.6489362
  lightness: 0.5808511
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#0B9444'
    - '#3A3A3A'
    - '#BEBEBE'
  rhythmicContrast: 0.4702128
name: HMC
