layout_spectrum: 0.2042553
typography_spectrum: 0.4893617
color:
  saturation: 0.6489362
  lightness: 0.5808511
  brandStrength: 0.4898375
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#0B9444'
    - '#3A3A3A'
    - '#BEBEBE'
  rhythmicContrast: 0.8846123
name: HMC
